name: Poker
version: '0.1.0.0'
category: Game
author: Tatsuki-I
maintainer: tatsuki.devel@gmail.com
copyright: 2017 Tatsuki-I
license: BSD3
github: Tatsuki-I/Poker
extra-source-files:
- README.md
library:
  source-dirs: src
  exposed-modules:
  - Poker
  - TexasHoldEm
  - Lib
  dependencies:
  - base >=4.7 && <5
  - random-shuffle
  - split
  - lens
executables:
  Poker:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    - -optc-O3
    - -Wall
    dependencies:
    - base
    - Poker
    - random-shuffle
tests:
  Poker-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - Poker
    - hspec
